stages:
  - login
  - build
  - deploy

login:
  stage: login
  only:
    - /^\d+(.\d+)*$/
    - main
  script:
    - docker login ${DOCKER_REGISTER_HOST} -u ${DOCKER_REGISTER_USERNAME} -p ${DOCKER_REGISTER_PASSWORD}

server-build-tag:
  stage: build
  only:
    - /^\d+(.\d+)*$/
  script:
    - docker buildx create --name gin-vue-admin-server-build || true
    - DOCKER_BUILDKIT=1 docker buildx build --builder gin-vue-admin-server-build --platform linux/amd64 -t ${DOCKER_REGISTER_HOST}/wuruiwm/gin-vue-admin-server:${CI_BUILD_TAG},${DOCKER_REGISTER_HOST}/wuruiwm/gin-vue-admin-server:latest --push -f deploy/server/Dockerfile .

web-build-tag:
  stage: build
  only:
    - /^\d+(.\d+)*$/
  script:
    - docker buildx create --name gin-vue-admin-web-build || true
    - DOCKER_BUILDKIT=1 docker buildx build --builder gin-vue-admin-web-build --platform linux/amd64 -t ${DOCKER_REGISTER_HOST}/wuruiwm/gin-vue-admin-web:${CI_BUILD_TAG},${DOCKER_REGISTER_HOST}/wuruiwm/gin-vue-admin-web:latest --push -f deploy/web/Dockerfile .

server-build-main:
  stage: build
  only:
    - main
  script:
    - docker buildx create --name gin-vue-admin-server-build || true
    - DOCKER_BUILDKIT=1 docker buildx build --builder gin-vue-admin-server-build --platform linux/amd64 -t ${DOCKER_REGISTER_HOST}/wuruiwm/gin-vue-admin-server:latest --push -f deploy/server/Dockerfile .

web-build-main:
  stage: build
  only:
    - main
  script:
    - docker buildx create --name gin-vue-admin-web-build || true
    - DOCKER_BUILDKIT=1 docker buildx build --builder gin-vue-admin-web-build --platform linux/amd64 -t ${DOCKER_REGISTER_HOST}/wuruiwm/gin-vue-admin-web:latest --push -f deploy/web/Dockerfile .

deploy-tag:
  stage: deploy
  only:
    - /^\d+(.\d+)*$/
  script:
    - sshpass -p ${K8S_MASTER_PASSWORD} ssh -p ${K8S_MASTER_PORT} -o StrictHostKeyChecking=no ${K8S_MASTER_USERNAME}@${K8S_MASTER_HOST}
      "kubectl set image -n gin-vue deployment gin-vue-admin gin-vue-admin-server=${DOCKER_REGISTER_HOST}/wuruiwm/gin-vue-admin-server:${CI_BUILD_TAG} gin-vue-admin-web=${DOCKER_REGISTER_HOST}/wuruiwm/gin-vue-admin-web:${CI_BUILD_TAG};
      && kubectl rollout restart -n gin-vue deployment gin-vue-admin;"

deploy-main:
  stage: deploy
  only:
    - main
  script:
    - sshpass -p ${K8S_MASTER_PASSWORD} ssh -p ${K8S_MASTER_PORT} -o StrictHostKeyChecking=no ${K8S_MASTER_USERNAME}@${K8S_MASTER_HOST}
      "kubectl set image -n gin-vue deployment gin-vue-admin gin-vue-admin-server=${DOCKER_REGISTER_HOST}/wuruiwm/gin-vue-admin-server:latest gin-vue-admin-web=${DOCKER_REGISTER_HOST}/wuruiwm/gin-vue-admin-web:latest
      && kubectl rollout restart -n gin-vue deployment gin-vue-admin"